# Generated by Django 5.1.1 on 2025-02-17 18:13

import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Sexos",
                "verbose_name_plural": "Sexo",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
