# Generated by Django 5.1.1 on 2025-02-22 23:27

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "cid10",
                    slth.db.models.CharField(max_length=255, verbose_name="CID10"),
                ),
            ],
            options={
                "verbose_name": "Doença",
                "verbose_name_plural": "Doenças",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="DoencaPreExistente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Doença Pré-Existente",
                "verbose_name_plural": "Doenças Pré-Existentes",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Escolaridade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Escolaridade",
                "verbose_name_plural": "Escolaridades",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(
                        max_length=2, unique=True, verbose_name="Código IBGE"
                    ),
                ),
                (
                    "sigla",
                    slth.db.models.CharField(
                        max_length=2, unique=True, verbose_name="Sigla"
                    ),
                ),
                (
                    "nome",
                    slth.db.models.CharField(
                        max_length=60, unique=True, verbose_name="Nome"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
                "ordering": ["nome"],
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Funcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Função",
                "verbose_name_plural": "Funções",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "codigo",
                    slth.db.models.CharField(max_length=255, verbose_name="Código"),
                ),
            ],
            options={
                "verbose_name": "Hospital",
                "verbose_name_plural": "Hospitais",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="PeriodoGestacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Período de Gestação",
                "verbose_name_plural": "Períodos de Gestação",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Raca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Raça",
                "verbose_name_plural": "Raças",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="SinalClinico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Sinal Clínico",
                "verbose_name_plural": "Sinais Clínicos",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="TipoLocal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Tipo de Local",
                "verbose_name_plural": "Tipos de Locais",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="TipoNotificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Tipo de Notificação",
                "verbose_name_plural": "Tipos de Notificação",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Zona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Zona",
                "verbose_name_plural": "Zonas",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AlterModelOptions(
            name="sexo",
            options={"verbose_name": "Sexo", "verbose_name_plural": "Sexos"},
        ),
        migrations.CreateModel(
            name="DetalheNotificacaoSurto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_primeiros_sintomas",
                    models.DateField(
                        verbose_name="Data dos 1º Sintomas do 1º Caso Suspeito"
                    ),
                ),
                (
                    "numero_casos_suspeitos",
                    slth.db.models.CharField(
                        max_length=255,
                        verbose_name="Número de Casos Suspeitos/Expostos",
                    ),
                ),
                (
                    "hipotese_diagnostica_1",
                    slth.db.models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="s1",
                        to="api.doenca",
                        verbose_name="1ª Hipótese Diagnóstica",
                    ),
                ),
                (
                    "hipotese_diagnostica_2",
                    slth.db.models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="s2",
                        to="api.doenca",
                        verbose_name="1ª Hipótese Diagnóstica",
                    ),
                ),
                (
                    "tipo_local",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.tipolocal",
                        verbose_name="Local Inicial da Ocorrência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalhamento de Notificação de Surto",
                "verbose_name_plural": "Detalhamentos de Notificação de Surto",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(
                        max_length=7, unique=True, verbose_name="Código IBGE"
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=60, verbose_name="Nome")),
                (
                    "estado",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.estado",
                        verbose_name="Estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Município",
                "verbose_name_plural": "Municípios",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="LocalInfeccao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pais",
                    slth.db.models.CharField(
                        default="Brasil", max_length=255, verbose_name="País"
                    ),
                ),
                (
                    "distrito",
                    slth.db.models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Distrito"
                    ),
                ),
                (
                    "bairro",
                    slth.db.models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Bairro"
                    ),
                ),
                (
                    "municipio",
                    slth.db.models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.municipio",
                        verbose_name="Município",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local de Infecção",
                "verbose_name_plural": "Locais de Infecção",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distrito",
                    slth.db.models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Distrito"
                    ),
                ),
                (
                    "bairro",
                    slth.db.models.CharField(max_length=255, verbose_name="Bairro"),
                ),
                (
                    "logradouro",
                    slth.db.models.CharField(max_length=255, verbose_name="Logradouro"),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Código do Logradouro",
                    ),
                ),
                (
                    "numero",
                    slth.db.models.CharField(max_length=255, verbose_name="Número"),
                ),
                (
                    "complemento",
                    slth.db.models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "latitude",
                    slth.db.models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    slth.db.models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Latitude"
                    ),
                ),
                (
                    "referencia",
                    slth.db.models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ponto de Referência",
                    ),
                ),
                ("cep", slth.db.models.CharField(max_length=255, verbose_name="CEP")),
                (
                    "telefone",
                    slth.db.models.CharField(max_length=255, verbose_name="Telefone"),
                ),
                (
                    "municipio",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.municipio",
                        verbose_name="Município",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="DetalhamentoNotificacaoIndividual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "idade",
                    slth.db.models.IntegerField(blank=True, verbose_name="Idade"),
                ),
                (
                    "cartao_sus",
                    slth.db.models.CharField(max_length=255, verbose_name="Cartão SUS"),
                ),
                (
                    "nome_mae",
                    slth.db.models.CharField(
                        max_length=255, verbose_name="Nome da Mãe"
                    ),
                ),
                (
                    "data_primeiros_sintomas",
                    slth.db.models.IntegerField(
                        verbose_name="Data dos Primeiros Sintomas"
                    ),
                ),
                (
                    "data_coleta_primeira_amostra",
                    models.DateField(
                        verbose_name="Data da Coleta da 1ª Amostra da Sorologia"
                    ),
                ),
                (
                    "data_coleta_outra_amostra",
                    models.DateField(
                        verbose_name="Data da Coleta da 1ª Amostra de Outra Amostra"
                    ),
                ),
                (
                    "tipo_exame",
                    slth.db.models.CharField(
                        max_length=255, verbose_name="Tipo de Exame"
                    ),
                ),
                ("obito", models.BooleanField(null=True, verbose_name="Óbito")),
                (
                    "contato_caso_semelhante",
                    models.BooleanField(
                        null=True, verbose_name="Contato com Caso Semelhante"
                    ),
                ),
                (
                    "presenca_exantema",
                    models.BooleanField(null=True, verbose_name="Presença de Exantema"),
                ),
                (
                    "data_inicio_exantema",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Início da Exantema"
                    ),
                ),
                (
                    "presenca_petequias_ou_sufusoes",
                    models.BooleanField(
                        null=True,
                        verbose_name="Presença de Petéquias ou Sufusões Hemorrágicas",
                    ),
                ),
                (
                    "realizado_liquor",
                    models.BooleanField(null=True, verbose_name="Realizado Líquor"),
                ),
                (
                    "resultado_bacterioscopia",
                    slth.db.models.CharField(
                        max_length=255, verbose_name="Resultado da Bacterioscopia"
                    ),
                ),
                (
                    "vacinado",
                    models.BooleanField(
                        null=True, verbose_name="Vacinado contra Doença"
                    ),
                ),
                (
                    "data_ultima_vacina",
                    models.DateField(verbose_name="Data da Última Dose da Vacina"),
                ),
                (
                    "hospitalizacao",
                    models.BooleanField(
                        null=True, verbose_name="Ocorreu Hospitalização"
                    ),
                ),
                (
                    "data_hospitalizacao",
                    models.DateField(verbose_name="Data da Hospitalização"),
                ),
                (
                    "sexo",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.sexo",
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "doencas_pre_existentes",
                    slth.db.models.ManyToManyField(
                        blank=True,
                        to="api.doencapreexistente",
                        verbose_name="Doenças Pré-Existentes",
                    ),
                ),
                (
                    "escolaridade",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.escolaridade",
                        verbose_name="Escolaridade",
                    ),
                ),
                (
                    "municio_hospitalizacao",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.municipio",
                        verbose_name="Município da Hospitalização",
                    ),
                ),
                (
                    "periodo_gestacao",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.periodogestacao",
                        verbose_name="Período de Gestação",
                    ),
                ),
                (
                    "raca",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.raca",
                        verbose_name="Raça",
                    ),
                ),
                (
                    "sinais_clinicos",
                    slth.db.models.ManyToManyField(
                        blank=True,
                        to="api.sinalclinico",
                        verbose_name="Sinais Clínicos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalhamento de Notificação Individual",
                "verbose_name_plural": "Detalhamentos de Notificação Individual",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Notificante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", slth.db.models.CharField(max_length=255, verbose_name="CPF")),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "funcao",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.funcao",
                        verbose_name="Função",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificante",
                "verbose_name_plural": "Notificantes",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="UnidadeSaude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(max_length=255, verbose_name="Código"),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "municipio",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.municipio",
                        verbose_name="Município",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade de Saúde",
                "verbose_name_plural": "Unidades de Saúde",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "detalhamento_individual",
                    slth.db.models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.detalhamentonotificacaoindividual",
                        verbose_name="Detalhamento Individual",
                    ),
                ),
                (
                    "detalhamento_surto",
                    slth.db.models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.detalhenotificacaosurto",
                        verbose_name="Detalhamento de Surto",
                    ),
                ),
                (
                    "doenca",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.doenca",
                        verbose_name="Doença",
                    ),
                ),
                (
                    "endereco",
                    slth.db.models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.endereco",
                        verbose_name="Endereço",
                    ),
                ),
                (
                    "possivel_local_infecao",
                    slth.db.models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.localinfeccao",
                        verbose_name="Possível Local de Infecção",
                    ),
                ),
                (
                    "notificante",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.notificante",
                        verbose_name="Notificante",
                    ),
                ),
                (
                    "tipo",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.tiponotificacao",
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "unidade",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.unidadesaude",
                        verbose_name="Unidade de Saúde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
