# Generated by Django 5.1.1 on 2025-02-23 06:43

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_doenca_doencapreexistente_escolaridade_estado_funcao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escolaridade",
            name="codigo",
            field=slth.db.models.CharField(
                default=None, max_length=255, verbose_name="Código"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="raca",
            name="codigo",
            field=slth.db.models.CharField(
                default=None, max_length=255, verbose_name="Código"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sexo",
            name="codigo",
            field=slth.db.models.CharField(
                default=None, max_length=255, verbose_name="Código"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tipolocal",
            name="codigo",
            field=slth.db.models.CharField(
                default=None, max_length=255, verbose_name="Código"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tiponotificacao",
            name="codigo",
            field=slth.db.models.CharField(
                default=None, max_length=255, verbose_name="Código"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zona",
            name="codigo",
            field=slth.db.models.CharField(
                default=None, max_length=255, verbose_name="Código"
            ),
            preserve_default=False,
        ),
    ]
