# Generated by Django 5.1.1 on 2025-03-14 23:36

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0003_rename_imunohistoquímica_notificacaoindividual_imunohistoquimica_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ApresentacaoClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(max_length=255, verbose_name="Código"),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Apresentação Clínica",
                "verbose_name_plural": "Apresentações Clínicas",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="ClassificacaoInfeccao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(max_length=255, verbose_name="Código"),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Classificação de Infecção",
                "verbose_name_plural": "Classificações de Infecção",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="CriterioConfirmacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(max_length=255, verbose_name="Código"),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Critério de Confirmação",
                "verbose_name_plural": "Critérios de Confirmação",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="SinalAlarme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(max_length=255, verbose_name="Código"),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Sinal de Alarme",
                "verbose_name_plural": "Sinais de Alarme",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="SinalComprometimentoOrgao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(max_length=255, verbose_name="Código"),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Sinal de Compromometimento dos Órgãos",
                "verbose_name_plural": "Sinais de Compromometimento dos Órgãos",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="SinalExtravasamentoPlasma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(max_length=255, verbose_name="Código"),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Sinal de Extravasamento do Plasma",
                "verbose_name_plural": "Sinais de Extravasamento do Plasma",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="SinalSangramentoGrave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(max_length=255, verbose_name="Código"),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Sinal de Sangramento Grave",
                "verbose_name_plural": "Sinais de Sangramento Grave",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="TipoEvolucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(max_length=255, verbose_name="Código"),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Tipo de Evolução",
                "verbose_name_plural": "Tipos de Evoluação",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_inicio_sinais_alarme",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data de Início dos Sinais de Alarme",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_inicio_sinais_graves",
            field=models.DateField(
                null=True, verbose_name="Data de Início dos Sinais de Gravidade"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="dengue_com_sinais_de_alarme",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Dengue com Sinais de Alarme"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="dengue_grave",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Dengue Grave"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="outros_orgaos_afetados",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Outros Órgãos"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="apresentacao_clinica",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.apresentacaoclinica",
                verbose_name="Apresentação Clínica",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="classificacao_infeccao",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.classificacaoinfeccao",
                verbose_name="Classificação da Infecção",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="criterio_confirmacao",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.criterioconfirmacao",
                verbose_name="Critério de Confirmação/Descarte",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="sinais_alarme_dengue",
            field=slth.db.models.ManyToManyField(
                blank=True, to="api.sinalalarme", verbose_name="Sinais de Alarme"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="sinais_comprometimento_orgaos",
            field=slth.db.models.ManyToManyField(
                blank=True,
                to="api.sinalcomprometimentoorgao",
                verbose_name="Sinais de Comprometimento dos Órgãos",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="sinais_extravasamento_plasma",
            field=slth.db.models.ManyToManyField(
                blank=True,
                to="api.sinalextravasamentoplasma",
                verbose_name="Sinais de Extravasamento do Plasma",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="sinais_sangramento_grave",
            field=slth.db.models.ManyToManyField(
                blank=True,
                to="api.sinalsangramentograve",
                verbose_name="Sinais de Sangramento Grave",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="evolucao_caso",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.tipoevolucao",
                verbose_name="Evolução do Caso",
            ),
        ),
    ]
