# Generated by Django 5.1.1 on 2025-02-23 06:57

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_escolaridade_codigo_raca_codigo_sexo_codigo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodogestacao",
            name="codigo",
            field=slth.db.models.CharField(
                default=None, max_length=255, verbose_name="Código"
            ),
            preserve_default=False,
        ),
    ]
