# Generated by Django 5.1.1 on 2025-02-23 09:21

import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_periodogestacao_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="contato_caso_semelhante",
            field=slth.db.models.BooleanField(
                choices=[(True, "Sim"), (False, "Não"), (None, "Não Informado")],
                null=True,
                verbose_name="Contato com Caso Semelhante",
            ),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="data_primeiros_sintomas",
            field=models.DateField(verbose_name="Data dos Primeiros Sintomas"),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="hospitalizacao",
            field=slth.db.models.BooleanField(
                choices=[(True, "Sim"), (False, "Não"), (None, "Não Informado")],
                null=True,
                verbose_name="Ocorreu Hospitalização",
            ),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="obito",
            field=slth.db.models.BooleanField(
                choices=[(True, "Sim"), (False, "Não"), (None, "Não Informado")],
                null=True,
                verbose_name="Óbito",
            ),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="presenca_exantema",
            field=slth.db.models.BooleanField(
                choices=[(True, "Sim"), (False, "Não"), (None, "Não Informado")],
                null=True,
                verbose_name="Presença de Exantema",
            ),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="presenca_petequias_ou_sufusoes",
            field=slth.db.models.BooleanField(
                choices=[(True, "Sim"), (False, "Não"), (None, "Não Informado")],
                null=True,
                verbose_name="Presença de Petéquias ou Sufusões Hemorrágicas",
            ),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="realizado_liquor",
            field=slth.db.models.BooleanField(
                choices=[(True, "Sim"), (False, "Não"), (None, "Não Informado")],
                null=True,
                verbose_name="Realizado Líquor",
            ),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="vacinado",
            field=slth.db.models.BooleanField(
                choices=[(True, "Sim"), (False, "Não"), (None, "Não Informado")],
                null=True,
                verbose_name="Vacinado contra Doença",
            ),
        ),
    ]
