# Generated by Django 5.1.1 on 2025-02-23 09:34

import django.db.models.deletion
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0005_alter_detalhamentonotificacaoindividual_contato_caso_semelhante_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="data_coleta_outra_amostra",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data da Coleta da 1ª Amostra de Outra Amostra",
            ),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="data_coleta_primeira_amostra",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data da Coleta da 1ª Amostra da Sorologia",
            ),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="data_hospitalizacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Hospitalização"
            ),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="data_ultima_vacina",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Última Dose da Vacina"
            ),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="municio_hospitalizacao",
            field=slth.db.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.municipio",
                verbose_name="Município da Hospitalização",
            ),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="resultado_bacterioscopia",
            field=slth.db.models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Resultado da Bacterioscopia",
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="detalhamento_individual",
            field=slth.db.models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.detalhamentonotificacaoindividual",
                verbose_name="Detalhamento Individual",
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="detalhamento_surto",
            field=slth.db.models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.detalhenotificacaosurto",
                verbose_name="Detalhamento de Surto",
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="endereco",
            field=slth.db.models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.endereco",
                verbose_name="Endereço",
            ),
        ),
    ]
