# Generated by Django 5.1.1 on 2025-02-23 09:41

import django.db.models.deletion
import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0006_alter_detalhamentonotificacaoindividual_data_coleta_outra_amostra_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="tipo_exame",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tipo de Exame"
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="possivel_local_infecao",
            field=slth.db.models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.localinfeccao",
                verbose_name="Possível Local de Infecção",
            ),
        ),
    ]
