# Generated by Django 5.1.1 on 2025-03-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_notificacaoindividual_autoctone"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_encerramento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Encerramento"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_obito",
            field=models.DateField(blank=True, null=True, verbose_name="Data do Óbito"),
        ),
    ]
