# Generated by Django 5.1.1 on 2025-02-24 07:25

import django.db.models.deletion
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_detalhamentonotificacaoindividual_tipo_exame_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="contato_caso_semelhante",
            field=models.BooleanField(
                null=True, verbose_name="Contato com Caso Semelhante"
            ),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="hospitalizacao",
            field=models.BooleanField(null=True, verbose_name="Ocorreu Hospitalização"),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="obito",
            field=models.BooleanField(default=False, verbose_name="Óbito"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="presenca_exantema",
            field=models.BooleanField(null=True, verbose_name="Presença de Exantema"),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="presenca_petequias_ou_sufusoes",
            field=models.BooleanField(
                null=True, verbose_name="Presença de Petéquias ou Sufusões Hemorrágicas"
            ),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="realizado_liquor",
            field=models.BooleanField(null=True, verbose_name="Realizado Líquor"),
        ),
        migrations.AlterField(
            model_name="detalhamentonotificacaoindividual",
            name="vacinado",
            field=models.BooleanField(null=True, verbose_name="Vacinado contra Doença"),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="detalhamento_individual",
            field=slth.db.models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.detalhamentonotificacaoindividual",
                verbose_name="Dados do Indivíduo",
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="detalhamento_surto",
            field=slth.db.models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.detalhenotificacaosurto",
                verbose_name="Dados do Surto",
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="endereco",
            field=slth.db.models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.endereco",
                verbose_name="Local da Notificação",
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="possivel_local_infecao",
            field=slth.db.models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.localinfeccao",
                verbose_name="Possível Local da Infecção",
            ),
        ),
    ]
