# Generated by Django 5.1.1 on 2025-03-23 14:50

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_notificacaoindividual_data_encerramento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doenca",
            name="modelo_ficha",
            field=slth.db.models.CharField(
                choices=[
                    ("ficha/padrao.html", "Padrão"),
                    ("ficha/dengue-chikungunya.html", "Dengue/Chikungunya"),
                ],
                max_length=255,
                null=True,
                verbose_name="Modelo da Ficha",
            ),
        ),
    ]
