# Generated by Django 5.1.1 on 2025-02-26 08:49

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_notificacao_detalhamento_individual_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificacaoindividual",
            old_name="data_coleta_exame_prnt_chikungunya",
            new_name="data_coleta_exame_prnt",
        ),
        migrations.RenameField(
            model_name="notificacaoindividual",
            old_name="resultado_exame_prnt_chikungunya",
            new_name="resultado_exame_prnt",
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="resultado_segunda_amostra_chikungunya",
            field=slth.db.models.IntegerField(
                blank=True,
                choices=[
                    (1, "Reagente"),
                    (2, "Não Reagente"),
                    (3, "Inconclusivo"),
                    (4, "Não Realizado"),
                ],
                null=True,
                verbose_name="Resultado da 2ª Amostra",
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="resultado_primeira_amostra_chikungunya",
            field=slth.db.models.IntegerField(
                blank=True,
                choices=[
                    (1, "Reagente"),
                    (2, "Não Reagente"),
                    (3, "Inconclusivo"),
                    (4, "Não Realizado"),
                ],
                null=True,
                verbose_name="Resultado da 1ª Amostra",
            ),
        ),
    ]
