# Generated by Django 5.1.1 on 2025-02-26 08:56

import django.db.models.deletion
import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0010_rename_data_coleta_exame_prnt_chikungunya_notificacaoindividual_data_coleta_exame_prnt_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="hospital",
            field=slth.db.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.hospital",
                verbose_name="Hospital",
            ),
        ),
    ]
