# Generated by Django 5.1.1 on 2025-02-27 18:34

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_notificacaoindividual_hospital"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocupacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(max_length=255, verbose_name="Código"),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Ocupação",
                "verbose_name_plural": "Ocupações",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="observacao",
            field=slth.db.models.TextField(
                blank=True, null=True, verbose_name="Observação"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="validada",
            field=models.BooleanField(blank=True, null=True, verbose_name="Validada"),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="longitude",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Longitude"
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="ocupacao_investigacao",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.ocupacao",
                verbose_name="Ocupação",
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="pais",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="s1",
                to="api.pais",
                verbose_name="País",
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="pais_infeccao",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="s2",
                to="api.pais",
                verbose_name="País da Infecção",
            ),
        ),
    ]
