# Generated by Django 5.1.1 on 2025-08-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_notificacaoindividual_token"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Gestor",
            new_name="Regulador",
        ),
        migrations.AlterModelOptions(
            name="regulador",
            options={"verbose_name": "Regulador", "verbose_name_plural": "Reguladores"},
        ),
    ]
