# Generated by Django 5.1.1 on 2025-08-02 23:24

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_rename_gestor_regulador_alter_regulador_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="GestorMunicipal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", slth.db.models.CharField(max_length=255, verbose_name="CPF")),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Gestor de Municipal",
                "verbose_name_plural": "Gestores Municipais",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="GestorUnidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", slth.db.models.CharField(max_length=255, verbose_name="CPF")),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Gestor de Unidade",
                "verbose_name_plural": "Gestores de Unidade",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name="notificante",
            name="email",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AddField(
            model_name="municipio",
            name="gestores",
            field=slth.db.models.ManyToManyField(blank=True, to="api.gestorunidade"),
        ),
        migrations.AddField(
            model_name="unidadesaude",
            name="gestores",
            field=slth.db.models.ManyToManyField(blank=True, to="api.gestorunidade"),
        ),
        migrations.CreateModel(
            name="SolicitacaoCadastroNotificante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", slth.db.models.CharField(max_length=255, verbose_name="CPF")),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "email",
                    slth.db.models.CharField(max_length=255, verbose_name="E-mail"),
                ),
                (
                    "data_solicitacao",
                    slth.db.models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Solicitação"
                    ),
                ),
                ("aprovada", models.BooleanField(null=True, verbose_name="Aprovada")),
                ("observacao", slth.db.models.TextField(verbose_name="Observação")),
                (
                    "funcao",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.funcao",
                        verbose_name="Função",
                    ),
                ),
                (
                    "unidades",
                    slth.db.models.ManyToManyField(
                        blank=True, to="api.unidadesaude", verbose_name="Unidades"
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Cadastro",
                "verbose_name_plural": "Solicitações de Cadastro",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
