# Generated by Django 5.1.1 on 2025-02-27 19:05

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_ocupacao_pais_notificacaoindividual_observacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadesaude",
            name="notificantes",
            field=slth.db.models.ManyToManyField(blank=True, to="api.notificante"),
        ),
    ]
