# Generated by Django 5.1.1 on 2025-02-27 19:25

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_unidadesaude_notificantes"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="cpf",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CPF"
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="cartao_sus",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Cartão SUS"
            ),
        ),
    ]
