# Generated by Django 5.1.1 on 2025-02-27 19:40

import django.db.models.deletion
import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_notificacaoindividual_cpf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="municipio_residencia",
            field=slth.db.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="s2",
                to="api.municipio",
                verbose_name="Município da Residência",
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="cep",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="municipio",
            field=slth.db.models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="s1",
                to="api.municipio",
                verbose_name="Município",
            ),
        ),
    ]
