# Generated by Django 5.1.1 on 2025-02-27 19:41

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_notificacaoindividual_municipio_residencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="bairro",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Bairro"
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="logradouro",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Logradouro"
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="numero_residencia",
            field=slth.db.models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Número da Residência",
            ),
        ),
    ]
