# Generated by Django 5.1.1 on 2025-08-05 06:50

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_municipio_reguladores"),
    ]

    operations = [
        migrations.AddField(
            model_name="gestormunicipal",
            name="email",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AddField(
            model_name="gestorunidade",
            name="email",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AddField(
            model_name="regulador",
            name="email",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="E-mail"
            ),
        ),
    ]
