# Generated by Django 5.1.1 on 2025-02-28 08:51

import django.db.models.deletion
import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_notificacaoindividual_bairro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="pais_infeccao",
            field=slth.db.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="s2",
                to="api.pais",
                verbose_name="País da Infecção",
            ),
        ),
    ]
