services:
  app: &app
    hostname: app
    env_file:
      - .env
    ports:
      - "8000:8000"
    build:
      context: src
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .docker/media:/opt/arbonotifica/media
      - .docker/static:/opt/arbonotifica/static
      - ./src/api:/opt/arbonotifica/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: curl http://127.0.0.1:8000/api/about/
    working_dir: /opt/arbonotifica
    entrypoint: ./entrypoint.sh

