services:
  app: &app
    hostname: app
    env_file:
      - .env
    ports:
      - "8000:8000"
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .deploy/media:/opt/deploy/media
      - .deploy/static:/opt/deploy/static
    healthcheck:
      test: curl http://127.0.0.1:8000/api/about/
    working_dir: /opt/deploy
    entrypoint: ./entrypoint.sh

