# Generated by Django 5.1.1 on 2025-03-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="vacinado2",
            field=models.BooleanField(null=True, verbose_name="Vacinado (2ª Dose)"),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="vacinado",
            field=models.BooleanField(null=True, verbose_name="Vacinado (1ª Dose)"),
        ),
    ]
