# Generated by Django 5.1.1 on 2025-03-14 09:29

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_notificacaoindividual_vacinado2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificacaoindividual",
            old_name="imunohistoquímica",
            new_name="imunohistoquimica",
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="cpf",
            field=slth.db.models.CharField(
                max_length=255, null=True, verbose_name="CPF", blank=True,
            ),
        ),
    ]
