# Generated by Django 5.1.1 on 2025-03-23 10:59

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_sinalcomprometimentoorgao_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="telefone",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Telefone"
            ),
        ),
    ]
