# Generated by Django 5.1.1 on 2025-03-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_hospital_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="autoctone",
            field=models.BooleanField(
                null=True, verbose_name="O caso é autóctone do município de residência?"
            ),
        ),
    ]
