# Generated by Django 5.1.1 on 2025-05-20 16:26

import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_doenca_modelo_ficha"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gestor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", slth.db.models.CharField(max_length=255, verbose_name="CPF")),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Gestor",
                "verbose_name_plural": "Gestores",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
