# Generated by Django 5.1.1 on 2025-06-19 09:28

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_gestor"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="token",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Token"
            ),
        ),
    ]
