# Generated by Django 5.1.1 on 2025-08-03 00:11

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_gestormunicipal_gestorunidade_notificante_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipio",
            name="gestores",
            field=slth.db.models.ManyToManyField(blank=True, to="api.gestormunicipal"),
        ),
    ]
