# Generated by Django 5.1.1 on 2025-08-05 06:29

import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_municipio_gestores"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", slth.db.models.CharField(max_length=255, verbose_name="CPF")),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "email",
                    slth.db.models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="E-mail"
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrador",
                "verbose_name_plural": "Administradores",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
