# Generated by Django 5.1.1 on 2025-08-05 06:41

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_administrador"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipio",
            name="reguladores",
            field=slth.db.models.ManyToManyField(blank=True, to="api.regulador"),
        ),
    ]
