# Generated by Django 5.1.3 on 2025-08-08 17:03

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_gestormunicipal_email_gestorunidade_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadesaude',
            name='notificantes',
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', slth.db.models.CharField(max_length=255, verbose_name='Código')),
                ('nome', slth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('notificantes', slth.db.models.ManyToManyField(blank=True, to='api.notificante')),
                ('unidade', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unidadesaude', verbose_name='Unidade de Saúde')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
