# Generated by Django 5.1.1 on 2025-08-09 10:59

import django.db.models.deletion
import slth
import slth.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_remove_unidadesaude_notificantes_equipe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitacaoCadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    slth.db.models.DateTimeField(
                        auto_created=True, null=True, verbose_name="Data da Solicitação"
                    ),
                ),
                ("cpf", slth.db.models.CharField(max_length=255, verbose_name="CPF")),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "email",
                    slth.db.models.CharField(max_length=255, verbose_name="E-mail"),
                ),
                (
                    "papel",
                    slth.db.models.CharField(
                        choices=[
                            ("gm", "Gestor Municipal"),
                            ("gu", "Gestor de Unidade"),
                            ("regulador", "Regulador"),
                            ("agente", "Agente de Endemia"),
                            ("notificante", "Notificante"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Papel",
                    ),
                ),
                ("aprovada", models.BooleanField(null=True, verbose_name="Aprovada")),
                (
                    "data_avaliacao",
                    slth.db.models.DateTimeField(
                        null=True, verbose_name="Data da Avaliação"
                    ),
                ),
                (
                    "observacao",
                    slth.db.models.TextField(
                        blank=True, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "avaliador",
                    slth.db.models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Avaliador",
                    ),
                ),
                (
                    "funcao",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.funcao",
                        verbose_name="Profissão/Função",
                    ),
                ),
                (
                    "municipio",
                    slth.db.models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.municipio",
                        verbose_name="Município",
                    ),
                ),
                (
                    "unidade",
                    slth.db.models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.unidadesaude",
                        verbose_name="Unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Cadastro",
                "verbose_name_plural": "Solicitações de Cadastro",
                "icon": "user-plus",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.DeleteModel(
            name="SolicitacaoCadastronotificante",
        ),
    ]
