# Generated by Django 5.1.1 on 2025-08-09 11:25

import django.db.models.deletion
import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_solicitacaocadastro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaocadastro",
            name="equipe",
            field=slth.db.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.equipe",
                verbose_name="Equipe",
            ),
        ),
        migrations.AlterField(
            model_name="administrador",
            name="email",
            field=slth.db.models.CharField(
                max_length=255, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="gestormunicipal",
            name="email",
            field=slth.db.models.CharField(
                max_length=255, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="gestorunidade",
            name="email",
            field=slth.db.models.CharField(
                max_length=255, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="email",
            field=slth.db.models.CharField(
                max_length=255, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="notificante",
            name="email",
            field=slth.db.models.CharField(
                max_length=255, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="regulador",
            name="email",
            field=slth.db.models.CharField(
                max_length=255, null=True, verbose_name="E-mail"
            ),
        ),
    ]
