# Generated by Django 5.1.1 on 2025-08-09 23:11

import django.db.models.deletion
import slth
import slth.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_solicitacaocadastro_equipe_alter_administrador_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_envio",
            field=models.DateField(blank=True, null=True, verbose_name="Data do Envio"),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="codigo",
            field=slth.db.models.CharField(max_length=255, verbose_name="INE"),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="data",
            field=models.DateField(verbose_name="Data da Notificação"),
        ),
        migrations.AlterField(
            model_name="unidadesaude",
            name="codigo",
            field=slth.db.models.CharField(max_length=255, verbose_name="CNES"),
        ),
        migrations.CreateModel(
            name="Devolucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", slth.db.models.DateTimeField(verbose_name="Data")),
                ("motivo", slth.db.models.TextField(verbose_name="Motivo")),
                (
                    "observao_correcao",
                    slth.db.models.TextField(
                        null=True, verbose_name="Observação da Correção"
                    ),
                ),
                (
                    "avaliador",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Avaliador",
                    ),
                ),
                (
                    "notificacao",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.notificacaoindividual",
                        verbose_name="Notificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devolução",
                "verbose_name_plural": "Devoluções",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
