# Generated by Django 5.1.1 on 2025-08-10 00:08

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_notificacaoindividual_data_envio_alter_equipe_codigo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devolucao",
            old_name="observao_correcao",
            new_name="observacao_correcao",
        ),
        migrations.AddField(
            model_name="devolucao",
            name="data_correcao",
            field=slth.db.models.DateTimeField(
                null=True, verbose_name="Data da Correção"
            ),
        ),
    ]
