# Generated by Django 5.1.1 on 2025-08-10 19:13

import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_rename_observao_correcao_devolucao_observacao_correcao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="devolvida",
            field=models.BooleanField(null=True, verbose_name="Devolvida"),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="email",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="E-mail"
            ),
        ),
    ]
