# Generated by Django 5.1.3 on 2025-08-21 08:55

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_notificacaoindividual_devolvida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='codigo',
            field=slth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='INE'),
        ),
    ]
