# Generated by Django 5.1.3 on 2025-10-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_equipe_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaoindividual',
            name='validada',
            field=models.BooleanField(blank=True, choices=[('', 'Selecione uma opção...'), (False, 'Não'), (True, 'Sim')], null=True, verbose_name='Validada'),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastro',
            name='aprovada',
            field=models.BooleanField(choices=[('', 'Selecione uma opção...'), (False, 'Não'), (True, 'Sim')], null=True, verbose_name='Aprovada'),
        ),
    ]
