# Generated by Django 5.1.3 on 2025-10-06 16:06

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_notificacaoindividual_validada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaoindividual',
            name='status',
            field=slth.db.models.CharField(choices=[['Em Análise', 'Em Análise'], ['Positivo', 'Positivo'], ['Negativo', 'Negativo']], default='Em Análise', max_length=255, verbose_name='Status'),
        ),
    ]
