# Generated by Django 5.1.3 on 2025-10-07 23:41

import django.db.models.deletion
import slth
import slth.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_notificacaoindividual_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_created=True, verbose_name='Data')),
                ('observacao', slth.db.models.TextField(verbose_name='Motivo')),
                ('notificacao', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.notificacaoindividual', verbose_name='Notificação')),
                ('notificante', slth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Notificante')),
            ],
            options={
                'verbose_name': 'Evolução',
                'verbose_name_plural': 'Evoluções',
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
