# Generated by Django 5.1.3 on 2025-10-08 00:00

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_evolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaoindividual',
            name='resultado_exame',
            field=slth.db.models.FileField(blank=True, null=True, upload_to='resultados_exames', verbose_name='Resultado do Exame'),
        ),
    ]
