# Generated by Django 5.1.1 on 2025-10-10 12:27

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_notificacaoindividual_resultado_exame"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="numero",
            field=slth.db.models.CharField(
                db_index=True, max_length=10, null=True, verbose_name="Número"
            ),
        ),
    ]
