# Generated by Django 5.1.1 on 2025-10-20 17:25

import django.db.models.deletion
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_notificacaoindividual_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_primeiros_sintomas_surto",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data dos 1º Sintomas do 1º Caso Suspeito",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="numero_casos_suspeitos_surto",
            field=slth.db.models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Número de Casos Suspeitos/Expostos",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="tipo_local_surto",
            field=slth.db.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.tipolocal",
                verbose_name="Local Inicial da Ocorrência",
            ),
        ),
        migrations.DeleteModel(
            name="NotificacaoSurto",
        ),
    ]
