# Generated by Django 5.1.1 on 2025-10-23 18:47

import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_notificacaoindividual_data_primeiros_sintomas_surto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="bloqueio",
            field=models.BooleanField(
                choices=[("", ""), (False, "Não"), (True, "Sim")],
                null=True,
                verbose_name="Bloqueio",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="tipo_bloqueio",
            field=slth.db.models.CharField(
                choices=[("Físico", "Físico"), ("Químico", "Químico"), ("Físico e Químico", "Físico e Químico")],
                max_length=255,
                null=True,
                verbose_name="Tipo de Bloqueio",
            ),
        ),
    ]
