# Generated by Django 5.1.1 on 2025-10-23 19:01

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_notificacaoindividual_bloqueio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", slth.db.models.CharField(max_length=255, verbose_name="CPF")),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "email",
                    slth.db.models.CharField(
                        max_length=255, null=True, verbose_name="E-mail"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agente de Endemias",
                "verbose_name_plural": "Agentes de Endemias",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="responsavel_bloqueio",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.agente",
                verbose_name="Responsável pelo Bloqueio",
            ),
        ),
        migrations.AddField(
            model_name="unidadesaude",
            name="agentes",
            field=slth.db.models.ManyToManyField(blank=True, to="api.agente", verbose_name="Agentes de Endemias"),
        ),
    ]
