# Generated by Django 5.1.1 on 2025-10-23 19:08

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_agente_notificacaoindividual_responsavel_bloqueio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_bloqueio",
            field=slth.db.models.DateTimeField(
                blank=True, null=True, verbose_name="Data do Bloqueio"
            ),
        ),
    ]
