# Generated by Django 5.1.1 on 2025-11-05 09:01

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_notificacaoindividual_data_bloqueio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadesaude",
            name="agentes",
        ),
        migrations.AddField(
            model_name="municipio",
            name="agentes",
            field=slth.db.models.ManyToManyField(
                blank=True, to="api.agente", verbose_name="Agentes de Endemias"
            ),
        ),
    ]
