# Generated by Django 5.1.1 on 2025-11-05 16:21

import django.db.models.deletion
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_remove_unidadesaude_agentes_municipio_agentes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="tipo_bloqueio",
            field=slth.db.models.CharField(
                blank=True,
                choices=[
                    ("Mecânico", "Mecânico"),
                    ("Químico", "Químico"),
                    ("Mecânico e Químico", "Mecânico e Químico"),
                ],
                max_length=255,
                null=True,
                verbose_name="Tipo de Bloqueio",
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="validada",
            field=models.BooleanField(
                blank=True,
                choices=[("", "Pendente de Avaliação"), (False, "Não"), (True, "Sim")],
                null=True,
                verbose_name="Validada",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaocadastro",
            name="unidade",
            field=slth.db.models.ForeignKey(
                blank=True,
                help_text="Obrigatório apenas para notificante.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.unidadesaude",
                verbose_name="Unidade",
            ),
        ),
    ]
