# Generated by Django 5.1.1 on 2025-11-09 19:35

import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_notificacaoindividual_tipo_bloqueio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", slth.db.models.CharField(max_length=255, verbose_name="CPF")),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "email",
                    slth.db.models.CharField(
                        max_length=255, null=True, verbose_name="E-mail"
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisor de Endemia",
                "verbose_name_plural": "Supervisores de Endemia",
                "icon": "person",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AlterField(
            model_name="municipio",
            name="agentes",
            field=slth.db.models.ManyToManyField(
                blank=True, to="api.agente", verbose_name="Agentes de Endemia"
            ),
        ),
        migrations.AddField(
            model_name="municipio",
            name="supervisores",
            field=slth.db.models.ManyToManyField(
                blank=True, to="api.supervisor", verbose_name="Supervisores de Endemia"
            ),
        ),
    ]
