# Generated by Django 5.1.1 on 2025-11-15 17:41

import django.db.models.deletion
import slth
import slth.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_supervisor_alter_municipio_agentes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MotivoPerdaPrazoBloqueio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Motivo de Perda de Prazo de Bloqueio",
                "verbose_name_plural": "Motivos de Perda de Prazo de Bloqueio",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="observacao_bloqueio",
            field=slth.db.models.TextField(
                blank=True,
                help_text="Informe algo que considera relevante durante a realização do bloqueio",
                null=True,
                verbose_name="Observação",
            ),
        ),
        migrations.CreateModel(
            name="Chamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_abertura",
                    slth.db.models.DateTimeField(
                        auto_created=True, verbose_name="Data da Abertura"
                    ),
                ),
                (
                    "descricao",
                    slth.db.models.TextField(
                        help_text="Descrição da solicitação ou problema",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "classificacao",
                    slth.db.models.CharField(
                        blank=True,
                        choices=[
                            ("", "Não-classificado"),
                            ("tecnico", "Técnico"),
                            ("negocio", "Negócio"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Classificação",
                    ),
                ),
                (
                    "data_atendimento",
                    slth.db.models.DateTimeField(
                        null=True, verbose_name="Data do Atendimento"
                    ),
                ),
                (
                    "atendido",
                    models.BooleanField(blank=True, null=True, verbose_name="Atendido"),
                ),
                (
                    "resolvido",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Resolvido"
                    ),
                ),
                (
                    "observacao",
                    slth.db.models.TextField(
                        blank=True, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "atendente",
                    slth.db.models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="r1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atendente",
                    ),
                ),
                (
                    "usuario",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chamado",
                "verbose_name_plural": "Chamados",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="motivo_perda_prazo_bloqueio",
            field=slth.db.models.ForeignKey(
                blank=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.motivoperdaprazobloqueio",
                verbose_name="Motivo da Perda de Prazo",
            ),
        ),
    ]
