# Generated by Django 5.1.1 on 2025-11-24 13:58

import django.db.models.deletion
import slth
import slth.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_motivoperdaprazobloqueio_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TermoUso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aceito",
                    models.BooleanField(
                        help_text="Concordo e aceito com os termos acima descritos.",
                        null=True,
                        verbose_name="Aceito",
                    ),
                ),
                (
                    "data_assinatura",
                    slth.db.models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Assinatura"
                    ),
                ),
                (
                    "user",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termo de Uso",
                "verbose_name_plural": "Termos de Uso",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
