# Generated by Django 5.1.1 on 2025-11-26 07:35

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_termouso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evolucao",
            name="data",
            field=slth.db.models.DateTimeField(auto_created=True, verbose_name="Data"),
        ),
    ]
