# Generated by Django 5.1.1 on 2025-12-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_alter_evolucao_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificacaoinfeccao",
            name="positivo",
            field=models.BooleanField(default=False, verbose_name="Positivo"),
        ),
    ]
