# Generated by Django 5.1.1 on 2025-12-05 08:33

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_classificacaoinfeccao_positivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Categoria de Video",
                "verbose_name_plural": "Categorias de Video",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local",
                    slth.db.models.CharField(max_length=255, verbose_name="Local"),
                ),
                (
                    "cep",
                    slth.db.models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="CEP"
                    ),
                ),
                (
                    "distrito",
                    slth.db.models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Distrito"
                    ),
                ),
                (
                    "bairro",
                    slth.db.models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Bairro"
                    ),
                ),
                (
                    "logradouro",
                    slth.db.models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Logradouro"
                    ),
                ),
                (
                    "codigo_logradouro",
                    slth.db.models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Código do Logradouro",
                    ),
                ),
                (
                    "numero",
                    slth.db.models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Número da Residência",
                    ),
                ),
                (
                    "complemento",
                    slth.db.models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "latitude",
                    slth.db.models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    slth.db.models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Longitude"
                    ),
                ),
                (
                    "referencia",
                    slth.db.models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ponto de Referência",
                    ),
                ),
                (
                    "municipio",
                    slth.db.models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.municipio",
                        verbose_name="Município da Residência",
                    ),
                ),
                (
                    "pais",
                    slth.db.models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.pais",
                        verbose_name="País",
                    ),
                ),
                (
                    "zona",
                    slth.db.models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.zona",
                        verbose_name="Zona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="endereco",
            field=slth.db.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.endereco",
                verbose_name="Endereço Pré-cadastrado",
            ),
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    slth.db.models.CharField(max_length=255, verbose_name="Título"),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(max_length=255, verbose_name="Código"),
                ),
                ("descricao", slth.db.models.TextField(verbose_name="Descrição")),
                (
                    "categoria",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.categoriavideo",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
