# Generated by Django 5.1.1 on 2025-12-05 18:34

import django.db.models.deletion
import slth
import slth.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_categoriavideo_endereco_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroLeituraResultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", slth.db.models.DateTimeField(verbose_name="Data/Hora")),
                (
                    "notificacao",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.notificacaoindividual",
                        verbose_name="Notificação",
                    ),
                ),
                (
                    "user",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
