# Generated by Django 5.1.1 on 2025-12-10 17:54

import django.db.models.deletion
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_registroleituraresultado"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="unidade_referencia",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="r1",
                to="api.unidadesaude",
                verbose_name="UBS de Referência",
            ),
        ),
        migrations.AddField(
            model_name="unidadesaude",
            name="referencia",
            field=models.BooleanField(default=False, verbose_name="Referência"),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="unidade",
            field=slth.db.models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.unidadesaude",
                verbose_name="Unidade de Saúde da Notificação",
            ),
        ),
    ]
