# Generated by Django 5.1.1 on 2025-12-17 07:59

import django.db.models.deletion
import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_notificacaoindividual_unidade_referencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_validacao",
            field=slth.db.models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Validação"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="responsavel_validacao",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.regulador",
                verbose_name="Responsável pelo Validação",
            ),
        ),
    ]
