# Generated by Django 5.1.1 on 2026-01-01 13:05

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_notificacaoindividual_data_validacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotivoDevolucaoBloqueio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Motivo para Devolução de Bloqueio",
                "verbose_name_plural": "Motivos para Devolução de Bloqueio",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_devolucao_bloqueio",
            field=slth.db.models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Devolução do Bloqueio"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="observacao_devolucao_bloqueio",
            field=slth.db.models.TextField(
                blank=True,
                help_text="Informe algo que considera relevante para a devolução de solicitação do bloqueio",
                null=True,
                verbose_name="Observação",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="motivo_devolucao_bloqueio",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.motivodevolucaobloqueio",
                verbose_name="Motivo para Devolução do Bloqueio",
            ),
        ),
    ]
