# Generated by Django 5.1.1 on 2026-01-02 14:45

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_motivodevolucaobloqueio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_atribuicao_bloqueio",
            field=slth.db.models.DateTimeField(
                blank=True, null=True, verbose_name="Data da Atribuição do Agente"
            ),
        ),
    ]
