# Generated by Django 5.1.1 on 2026-01-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_notificacaoindividual_data_atribuicao_bloqueio"),
    ]

    operations = [
        migrations.AddField(
            model_name="motivoperdaprazobloqueio",
            name="encerrar_chamado",
            field=models.BooleanField(default=False, verbose_name="Encerrar Chamado"),
        ),
    ]
