# Generated by Django 5.1.1 on 2026-01-16 07:27

import django.db.models.deletion
import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_motivoperdaprazobloqueio_encerrar_chamado"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_perda_prazo_bloqueio",
            field=slth.db.models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Data da Justificativa da Perda de Prazo",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="observacao_perda_prazo_bloqueio",
            field=slth.db.models.TextField(
                blank=True,
                help_text="Informe algo que considera relevante sobre a perda de prazo do bloqueio",
                null=True,
                verbose_name="Observação da Perda do Prazo",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="responsavel_perda_prazo_bloqueio",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.supervisor",
                verbose_name="Responsável pela Justificativa da Perda de Prazo",
            ),
        ),
    ]
