# Generated by Django 5.1.1 on 2026-01-25 10:20

import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_notificacaoindividual_data_perda_prazo_bloqueio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_alta",
            field=models.DateField(blank=True, null=True, verbose_name="Data da Alta"),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="latitude_bloqueio",
            field=slth.db.models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Latitude do Bloqueio",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="longitude_bloqueio",
            field=slth.db.models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Longitude do Bloqueio",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="numero_prontuario",
            field=slth.db.models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Número do Prontuário",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="sinan",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Número da Notificação no SINAN"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="situacao_hospitalar",
            field=slth.db.models.CharField(
                choices=[
                    ("Internado", "Internado"),
                    ("Alta", "Alta"),
                    ("Óbito", "Óbito"),
                ],
                max_length=255,
                null=True,
                blank=True,
                verbose_name="Situação Hospitalar",
            ),
        ),
    ]
