# Generated by Django 5.1.1 on 2026-02-01 15:15

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_notificacaoindividual_data_alta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemanaEpidemiologica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", slth.db.models.IntegerField(verbose_name="Ano")),
                ("numero", slth.db.models.IntegerField(verbose_name="Número")),
                ("inicio", models.DateField(verbose_name="Início")),
                ("termino", models.DateField(verbose_name="Término")),
            ],
            options={
                "verbose_name": "Semana Epidemiológica",
                "verbose_name_plural": "Semanas Epidemiológicas",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.RemoveField(
            model_name="notificacaoindividual",
            name="bloqueio",
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="resultado_exame2",
            field=slth.db.models.FileField(
                blank=True,
                null=True,
                upload_to="resultados_exames",
                verbose_name="Resultado do 2º Exame",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="resultado_exame3",
            field=slth.db.models.FileField(
                blank=True,
                null=True,
                upload_to="resultados_exames",
                verbose_name="Resultado do 3º Exame",
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="resultado_exame",
            field=slth.db.models.FileField(
                blank=True,
                null=True,
                upload_to="resultados_exames",
                verbose_name="Resultado do 1º Exame",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="semana_epidemiologica",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.semanaepidemiologica",
                verbose_name="Semana Epidemiológica",
            ),
        ),
    ]
