# Generated by Django 5.1.1 on 2026-02-08 14:36

import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_semanaepidemiologica_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="registrado_sinan",
            field=models.BooleanField(
                default=False, verbose_name="Registrado no SINAN"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="status_infeccao",
            field=slth.db.models.CharField(
                choices=[
                    ("Em Análise", "Em Análise"),
                    ("Positivo", "Positivo"),
                    ("Negativo", "Negativo"),
                ],
                default="Em Análise",
                max_length=255,
                verbose_name="Status da Infecção",
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="status",
            field=slth.db.models.CharField(
                choices=[("Em Análise", "Em Análise"), ("Finalizado", "Finalizado")],
                default="Em Análise",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
