# Generated by Django 5.1.1 on 2026-02-08 15:18

import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_notificacaoindividual_registrado_sinan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReguladorUnidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", slth.db.models.CharField(max_length=255, verbose_name="CPF")),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "email",
                    slth.db.models.CharField(
                        max_length=255, null=True, verbose_name="E-mail"
                    ),
                ),
            ],
            options={
                "verbose_name": "Regulador de Unidade",
                "verbose_name_plural": "Reguladores de Unidade",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.AddField(
            model_name="unidadesaude",
            name="reguladores",
            field=slth.db.models.ManyToManyField(blank=True, to="api.reguladorunidade"),
        ),
    ]
