# Generated by Django 5.1.1 on 2026-02-12 08:01

import django.db.models.deletion
import slth.db.models
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_reguladorunidade_unidadesaude_reguladores"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doenca",
            name="sigla",
            field=slth.db.models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Sigla"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_cancelamento",
            field=slth.db.models.DateTimeField(
                blank=True, null=True, verbose_name="Data do Cancelamento"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="observacao_cancelamento",
            field=slth.db.models.TextField(
                blank=True,
                help_text="Informe o motivo pelo qual a ficha está sendo cancelada",
                null=True,
                verbose_name="Observação",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="responsavel_pelo_cancelamento",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rc1",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável pelo Cancelamento",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="responsavel_pelo_envio",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável pelo Envio",
            ),
        ),
    ]
