# Generated by Django 5.1.1 on 2026-02-12 08:02

from django.db import migrations

def migrate(apps, schema):
    User =  apps.get_model('auth', 'User')
    NotificacaoIndividual = apps.get_model('api', 'NotificacaoIndividual')
    for notificacao in NotificacaoIndividual.objects.filter(data_envio__isnull=False):
        notificacao.responsavel_pelo_envio = User.objects.get(username=notificacao.notificante.cpf)
        notificacao.save()

def unmigrate(apps, schema):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_doenca_sigla_notificacaoindividual_data_cancelamento_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate, unmigrate)
    ]
