# Generated by Django 5.1.1 on 2026-03-16 11:56

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_auto_20260212_0802"),
    ]

    operations = [
        migrations.AddField(
            model_name="semanaepidemiologica",
            name="descricao",
            field=slth.db.models.CharField(
                max_length=255, null=True, verbose_name="Descrição"
            ),
        ),
    ]
