# Generated by Django 5.1.1 on 2026-03-16 12:01

from django.db import migrations
from django.db import transaction
from datetime import timedelta, date

def migrate(apps, editor):
    NotificacaoIndividual = apps.get_model('api', 'notificacaoindividual')
    SemanaEpidemiologica = apps.get_model('api', 'semanaepidemiologica')
    with transaction.atomic():
        numero = 1
        data = date(2026, 1, 3)
        while True:
            inicio = data + timedelta(days=1)
            fim = inicio + timedelta(days=6)
            print("{}ª semana: de {} a {}".format(numero, inicio.strftime("%d/%m/%Y"), fim.strftime("%d/%m/%Y")))
            data = fim
            numero = numero + 1
            qs = NotificacaoIndividual.objects.filter(data_primeiros_sintomas__gte=inicio, data_primeiros_sintomas__lte=fim)
            semana_epidemiologica = SemanaEpidemiologica.objects.get_or_create(ano=inicio.year, numero=numero, inicio=inicio, termino=fim)[0]
            qs.update(semana_epidemiologica=semana_epidemiologica)
            if data.year == 2027: break

def unmigrate(apps, editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_semanaepidemiologica_descricao"),
    ]

    operations = [
        migrations.RunPython(migrate, unmigrate)
    ]
