# Generated by Django 5.1.1 on 2026-03-24 07:52

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20260316_1201'),
    ]

    operations = [
        UnaccentExtension()
    ]
