# Generated by Django 5.1.1 on 2026-04-02 10:04

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_auto_20260324_0752"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="resultado_exame4",
            field=slth.db.models.FileField(
                blank=True,
                null=True,
                upload_to="resultados_exames",
                verbose_name="Resultado do 4º Exame",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="resultado_exame5",
            field=slth.db.models.FileField(
                blank=True,
                null=True,
                upload_to="resultados_exames",
                verbose_name="Resultado do 5º Exame",
            ),
        ),
    ]
