# Generated by Django 5.1.1 on 2026-04-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_notificacaoindividual_resultado_exame4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_vacina_chikungunya",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Vacina da Chikungunya"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="tomou_vacina_chikungunya",
            field=models.BooleanField(
                default=False, verbose_name="Tomou vacina de Chikungunya?"
            ),
        ),
    ]
