# Generated by Django 5.1.1 on 2026-04-18 10:48

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_notificacaoindividual_data_vacina_chikungunya_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="resumo_clinico",
            field=slth.db.models.TextField(
                blank=True, null=True, verbose_name="Resumo Clínico"
            ),
        ),
    ]
