# Generated by Django 5.1.1 on 2026-04-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_notificacaoindividual_resumo_clinico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="tomou_vacina_chikungunya",
            field=models.BooleanField(
                null=True, verbose_name="Tomou vacina de Chikungunya?"
            ),
        ),
    ]
