# Generated by Django 5.1.1 on 2026-06-19 15:57

import django.db.models.deletion
import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_alter_notificacaoindividual_tomou_vacina_chikungunya"),
    ]

    operations = [
        migrations.AddField(
            model_name="evolucao",
            name="unidade",
            field=slth.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.unidadesaude",
                verbose_name="Unidade",
            ),
        ),
    ]
