# Generated by Django 5.1.1 on 2026-07-01 17:08

import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_evolucao_unidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacaoindividual",
            name="motivo_ausencia_sinais_clinicos",
            field=slth.db.models.TextField(
                blank=True,
                help_text="Preencher apenas nos casos em que nenhum sinal clínico é informado.",
                null=True,
                verbose_name="Motivo da Ausência de Sinais Clínicos",
            ),
        ),
        migrations.AlterField(
            model_name="notificacaoindividual",
            name="sinais_clinicos",
            field=slth.db.models.ManyToManyField(
                blank=True, to="api.sinalclinico", verbose_name="Sinais Clínicos"
            ),
        ),
    ]
