# Generated by Django 5.1.1 on 2026-07-14 19:23

import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_notificacaoindividual_motivo_ausencia_sinais_clinicos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArquivoExportacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    slth.db.models.CharField(
                        blank=True, max_length=255, verbose_name="Nome"
                    ),
                ),
                (
                    "arquivo",
                    slth.db.models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exportacao",
                        verbose_name="Arquivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo de Exportação",
                "verbose_name_plural": "Arquivos de Exportação",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
