# Generated by Django 5.1.1 on 2026-07-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_arquivoexportacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="arquivoexportacao",
            name="data_fim_envio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Fim do Envio das Fichas"
            ),
        ),
        migrations.AddField(
            model_name="arquivoexportacao",
            name="data_inicio_envio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Início do Envio das Fichas"
            ),
        ),
    ]
