# Generated by Django 5.1.1 on 2026-08-20 12:40

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_arquivoexportacao_data_fim_envio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bairro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    slth.db.models.CharField(max_length=255, verbose_name="Código"),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Bairro",
                "verbose_name_plural": "Bairros",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="MapeamentoBairro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "bairro",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.bairro",
                        verbose_name="Bairro",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapeamento de Bairro",
                "verbose_name_plural": "Mapeamento de Bairros",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
