# Generated by Django 5.1.1 on 2026-09-04 10:04

import django.db.models.deletion
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_bairro_mapeamentobairro"),
    ]

    operations = [
        migrations.AddField(
            model_name="bairro",
            name="municipio",
            field=slth.db.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.municipio",
                verbose_name="Município",
            ),
        ),
        migrations.AddField(
            model_name="mapeamentobairro",
            name="municipio",
            field=slth.db.models.CharField(
                max_length=255, null=True, verbose_name="Município"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_amostra_zica",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Coleta"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="data_rt_pcr_zica",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Coleta RT-PCR"
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="resultado_amostra_zica",
            field=slth.db.models.IntegerField(
                blank=True,
                choices=[
                    (1, "Positivo"),
                    (2, "Negativo"),
                    (3, "Inconclusivo"),
                    (4, "Não Realizado"),
                ],
                null=True,
                verbose_name="Resultado Coleta",
            ),
        ),
        migrations.AddField(
            model_name="notificacaoindividual",
            name="resultado_rt_pcr_zica",
            field=slth.db.models.IntegerField(
                blank=True,
                choices=[
                    (1, "Positivo"),
                    (2, "Negativo"),
                    (3, "Inconclusivo"),
                    (4, "Não Realizado"),
                ],
                null=True,
                verbose_name="Resultado RT-PCR",
            ),
        ),
    ]
