# Generated by Django 5.1.1 on 2026-09-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_bairro_municipio_mapeamentobairro_municipio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bairro",
            name="codigo",
        ),
    ]
